---
title: Current state
config:
flowchart:
    defaultRenderer: elk
---
flowchart BT
aws_eip.nat_eip
aws_internet_gateway.demo_igw
aws_main_route_table_association.demo_rta
aws_nat_gateway.nat_gw
aws_route.bastion_rt_igw
aws_route.demo_rt_igw
aws_route.mesos_master_rt_igw
aws_route.mesos_slave_rt_igw
aws_route.monitor_rt_igw
aws_route.nat_igw_route
aws_route.traefik_rt_igw
aws_route.zookeeper_rt_igw
aws_route53_zone_association.private-zone-association
aws_route_table.bastion_rt
aws_route_table.demo_rt
aws_route_table.mesos_master_rt
aws_route_table.mesos_slave_rt
aws_route_table.monitor_rt
aws_route_table.nat_gw_rt
aws_route_table.traefik_rt
aws_route_table.vpn_rt
aws_route_table.zookeeper_rt
aws_route_table_association.bastion_rta
aws_route_table_association.mesos_master_rta
aws_route_table_association.mesos_slave_rta
aws_route_table_association.monitor_rta
aws_route_table_association.traefik_rta
aws_route_table_association.vpn_rta
aws_route_table_association.zookeeper_rta
aws_security_group.bastion_sg
aws_security_group.elb_sg
aws_security_group.mesos_master_sg
aws_security_group.mesos_slave_sg
aws_security_group.monitor_sg
aws_security_group.traefik_sg
aws_security_group.vpn_sg
aws_security_group.zookeeper_sg
aws_security_group_rule.allow_from_master
aws_security_group_rule.allow_from_zookeeper
aws_subnet.bastion_subnet
aws_subnet.elb_subnet
aws_subnet.mesos_master_subnet
aws_subnet.mesos_slave_subnet
aws_subnet.monitor_subnet
aws_subnet.nat_gw_subnet
aws_subnet.traefik_subnet
aws_subnet.vpn_subnet
aws_subnet.zookeeper_subnet
aws_vpc.demo
aws_internet_gateway.demo_igw --> aws_vpc.demo
aws_main_route_table_association.demo_rta --> aws_route_table.demo_rt
aws_main_route_table_association.demo_rta --> aws_vpc.demo
aws_nat_gateway.nat_gw --> aws_subnet.nat_gw_subnet
aws_nat_gateway.nat_gw --> aws_internet_gateway.demo_igw
aws_nat_gateway.nat_gw --> aws_eip.nat_eip
aws_route.bastion_rt_igw --> aws_route_table.bastion_rt
aws_route.bastion_rt_igw --> aws_internet_gateway.demo_igw
aws_route.demo_rt_igw --> aws_route_table.demo_rt
aws_route.demo_rt_igw --> aws_internet_gateway.demo_igw
aws_route.mesos_master_rt_igw --> aws_route_table.mesos_master_rt
aws_route.mesos_master_rt_igw --> aws_internet_gateway.demo_igw
aws_route.mesos_slave_rt_igw --> aws_route_table.mesos_slave_rt
aws_route.mesos_slave_rt_igw --> aws_internet_gateway.demo_igw
aws_route.monitor_rt_igw --> aws_internet_gateway.demo_igw
aws_route.monitor_rt_igw --> aws_route_table.monitor_rt
aws_route.nat_igw_route --> aws_route_table.nat_gw_rt
aws_route.nat_igw_route --> aws_internet_gateway.demo_igw
aws_route.traefik_rt_igw --> aws_internet_gateway.demo_igw
aws_route.traefik_rt_igw --> aws_route_table.traefik_rt
aws_route.zookeeper_rt_igw --> aws_internet_gateway.demo_igw
aws_route.zookeeper_rt_igw --> aws_route_table.zookeeper_rt
aws_route53_zone_association.private-zone-association --> aws_vpc.demo
aws_route_table.bastion_rt --> aws_vpc.demo
aws_route_table.demo_rt --> aws_vpc.demo
aws_route_table.mesos_master_rt --> aws_vpc.demo
aws_route_table.mesos_slave_rt --> aws_vpc.demo
aws_route_table.monitor_rt --> aws_vpc.demo
aws_route_table.nat_gw_rt --> aws_vpc.demo
aws_route_table.traefik_rt --> aws_vpc.demo
aws_route_table.vpn_rt --> aws_internet_gateway.demo_igw
aws_route_table.vpn_rt --> aws_vpc.demo
aws_route_table.zookeeper_rt --> aws_vpc.demo
aws_route_table_association.bastion_rta --> aws_route_table.bastion_rt
aws_route_table_association.bastion_rta --> aws_subnet.bastion_subnet
aws_route_table_association.mesos_master_rta --> aws_route_table.mesos_master_rt
aws_route_table_association.mesos_master_rta --> aws_subnet.mesos_master_subnet
aws_route_table_association.mesos_slave_rta --> aws_route_table.mesos_slave_rt
aws_route_table_association.mesos_slave_rta --> aws_subnet.mesos_slave_subnet
aws_route_table_association.monitor_rta --> aws_subnet.monitor_subnet
aws_route_table_association.monitor_rta --> aws_route_table.monitor_rt
aws_route_table_association.traefik_rta --> aws_subnet.traefik_subnet
aws_route_table_association.traefik_rta --> aws_route_table.traefik_rt
aws_route_table_association.vpn_rta --> aws_subnet.vpn_subnet
aws_route_table_association.vpn_rta --> aws_route_table.vpn_rt
aws_route_table_association.zookeeper_rta --> aws_subnet.zookeeper_subnet
aws_route_table_association.zookeeper_rta --> aws_route_table.zookeeper_rt
aws_security_group.bastion_sg --> aws_security_group.vpn_sg
aws_security_group.bastion_sg --> aws_vpc.demo
aws_security_group.elb_sg --> aws_vpc.demo
aws_security_group.mesos_master_sg --> aws_security_group.vpn_sg
aws_security_group.mesos_master_sg --> aws_security_group.traefik_sg
aws_security_group.mesos_master_sg --> aws_vpc.demo
aws_security_group.mesos_master_sg --> aws_security_group.mesos_slave_sg
aws_security_group.mesos_slave_sg --> aws_security_group.vpn_sg
aws_security_group.mesos_slave_sg --> aws_vpc.demo
aws_security_group.monitor_sg --> aws_security_group.vpn_sg
aws_security_group.monitor_sg --> aws_security_group.bastion_sg
aws_security_group.monitor_sg --> aws_vpc.demo
aws_security_group.traefik_sg --> aws_security_group.vpn_sg
aws_security_group.traefik_sg --> aws_vpc.demo
aws_security_group.traefik_sg --> aws_security_group.elb_sg
aws_security_group.vpn_sg --> aws_vpc.demo
aws_security_group.zookeeper_sg --> aws_security_group.mesos_master_sg
aws_security_group.zookeeper_sg --> aws_security_group.vpn_sg
aws_security_group.zookeeper_sg --> aws_vpc.demo
aws_security_group.zookeeper_sg --> aws_security_group.mesos_slave_sg
aws_security_group_rule.allow_from_master --> aws_security_group.mesos_master_sg
aws_security_group_rule.allow_from_master --> aws_security_group.mesos_slave_sg
aws_security_group_rule.allow_from_zookeeper --> aws_security_group.mesos_master_sg
aws_security_group_rule.allow_from_zookeeper --> aws_security_group.zookeeper_sg
aws_subnet.bastion_subnet --> aws_vpc.demo
aws_subnet.elb_subnet --> aws_vpc.demo
aws_subnet.mesos_master_subnet --> aws_vpc.demo
aws_subnet.mesos_slave_subnet --> aws_vpc.demo
aws_subnet.monitor_subnet --> aws_vpc.demo
aws_subnet.nat_gw_subnet --> aws_vpc.demo
aws_subnet.traefik_subnet --> aws_vpc.demo
aws_subnet.vpn_subnet --> aws_vpc.demo
aws_subnet.zookeeper_subnet --> aws_vpc.demo
